" vim: foldmethod=marker

"{{{1 Initial config
set shell=/bin/sh "Vim must operate in a POSIX compliant shell, if you're not in one, hooo boy
set nocompatible  "Might as well actually use Vim instead of Vi

"{{{1 Vundle Settings
filetype off      "Vundle needs this off, we turn it on later

set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#rc()

"So vundle will update itself
Bundle 'gmarik/Vundle.vim'

"{{{2 Scroll Colors - For selecting themes
" use the COLORSCROLL command to activate it test colorthemes
Bundle 'ScrollColors'

"{{{3 xoria256 colorscheme - Super awesome
Bundle 'vim-scripts/xoria256.vim'

"{{{2 Indent Guides - Provides alternating bars for indentation
" This plugin provides 3 commands, all prefixed with IndentGuides
Bundle 'Indent-Guides'
	let g:indent_guides_enable_on_vim_startup = 1
	let g:indent_guides_color_change_percent = 5

"{{{2 editorConfig - Reads .editorconfig files and obeys
Bundle 'editorconfig/editorconfig-vim'

"{{{2 Tabularize - Run :Tab /pattern to format tabular data
Bundle 'godlygeek/tabular'

"{{{2 NERD Commenter - An insanely over the top commenting plugin.
Bundle 'scrooloose/nerdcommenter'

"{{{2 Airline - the sexy little bar at the bottom
Bundle 'bling/vim-airline'
	"Set this to one if you have a Powerline patched font (google it)
	let g:airline_powerline_fonts = 1
	set laststatus=2
	set noshowmode

"{{{2 Fugitive - For sexy git integration
Bundle 'fugitive.vim'

"{{{2 Sensible - This seems sensible, (a smattering of sensible defaults)
Bundle 'tpope/vim-sensible'

"{{{2 Unimpared - A list of symetric hotkeys
" Primarily used to bubble lines, but lots of cool features
" check out :h unimpaired
Bundle 'tpope/vim-unimpaired'

	"{{{3 Bubbling commands - Ctrl + up or down to bubble selections
	nmap <C-up> [e
	nmap <C-down> ]e
	vmap <C-up> [egv
	vmap <C-down> ]egv

"{{{2 match it - Makes it so % jumps XML tags correctly (and more)
Bundle 'matchit.zip'

"{{{2 ZenCoding - for fast HTML completions
Bundle "mattn/emmet-vim"

"{{{2 css-color - Changes background of hex squares to represent color
Bundle 'skammer/vim-css-color'

"{{{2 YouCompleteMe - Advanced code completion for C languages
Bundle 'Valloric/YouCompleteMe'
	"let g:ycm_autoclose_previw_window_after_insertion = 1
	"Special instructions: When YCM updates, it often needs a recompile
	"By default, that is done by running ~/.vim/bundle/YouCompleteMe/install.sh

"{{{2 vim-go - An entire development environment package for golang in vim
Bundle 'fatih/vim-go'
	au FileType go nmap <Leader>gb <Plug>(go-doc-browser)

"{{{2 tagbar - Displays all of the tags generated by ctags/gotags. press F8
Bundle 'majutsushi/tagbar'
	nmap <F8> :TagbarToggle<CR>

"{{{2 Easymotion - Allows you to add \ before a move command to do a fastmove!
Bundle 'Lokaltog/vim-easymotion'
	"Single leader prefix
	map <Leader> <Plug>(easymotion-prefix)
	"easymotion search
	map  / <Plug>(easymotion-sn)
	omap / <Plug>(easymotion-tn)
 	map  n <Plug>(easymotion-next)
 	map  N <Plug>(easymotion-prev)
	"bothdirection search
	map  s <Plug>(easymotion-s)

"{{{2 CtrlP - Like Command T, a file explorer, use CTRL-T
Bundle 'kien/ctrlp.vim'
	let g:ctrlp_map = '<c-t>'

"{{{2 Syntax bundles - All the bundles that provide syntax stuff
Bundle 'Soares/fish.vim'
Bundle 'octave.vim'
Bundle 'xolox/vim-misc'
Bundle 'xolox/vim-lua-ftplugin'
Bundle 'tfnico/vim-gradle'
Bundle 'wting/rust.vim'
Bundle 'cakebaker/scss-syntax.vim'
Bundle 'kchmck/vim-coffee-script'
Bundle 'tpope/vim-markdown'
Bundle 'nelstrom/vim-markdown-folding'
Bundle 'ipoddubny/asterisk-vim'
Bundle "Matt-Deacalion/vim-systemd-syntax"

"{{{1 My Settings
set number		"Numberlines
set guifont=Droid\ Sans\ Mono\ for\ Powerline\ 10
set history=700
set tabstop=4
set shiftwidth=4
set scrolloff=7
set foldmethod=syntax
let javaScript_fold=1         " JavaScript
let perl_fold=1               " Perl
let php_folding=1             " PHP
let r_syntax_folding=1        " R
let ruby_fold=1               " Ruby
let sh_fold_enabled=1         " sh
let vimsyn_folding='af'       " Vim script
let xml_syntax_folding=1      " XML

"{{{2 When searching, center the screen on the found item
"map N Nzz
"map n nzz

"{{{2 Sudo escalation commands - :W will sudo write. :Wq doesn't work :(
command! W w !sudo tee % >/dev/null

"{{{1 Some gui/nongui independent settings
"colorscheme xoria256
if has("gui_running")
	colorscheme xoria256
	set go+=c
	set go-=e
	set go-=m
	set go-=T
else
	set t_Co=256
	colorscheme desert
	set ttimeoutlen=10
	augroup FastEscape
		autocmd!
		au InsertEnter * set timeoutlen=0
		au InsertLeave * set timeoutlen=1000
	augroup END
endif

filetype plugin indent on
" vim: foldmethod=marker
